export HADOOP_HOME=/usr/local/hadoop
export HADOOP_YARN_HOME=${HADOOP_HOME}
export HADOOP_CONF_DIR=${HADOOHADOOP_HOMEP_PREFIX}/etc/hadoop
export HADOOP_LOG_DIR=${HADOOP_YARN_HOME}/logs
export HADOOP_IDENT_STRING=root
export HADOOP_MAPRED_IDENT_STRING=root
export PATH=${HADOOP_HOME}/bin:${PATH}